#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
#Gradle
org.gradle.jvmargs=-Xmx8192M -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true
#App Version
appVersion=1.0.0
# Workaround for Shadow plugin
mainClassName=cc.thevar.acc.ApplicationKt
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
# Force SDK location to avoid service errors
org.gradle.project.android.sdk.path=/home/ramadoss/Android/Sdk
